name: Mastermind X Crawler

on:
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🚀 Run Mastermind X Crawler
        run: |
       echo "===== DEBUG START ====="
        pwd
       ls -la
       echo "===== RUNNING CRAWLER ====="
       node crawler.js
       echo "===== DEBUG END ====="

      - name: 📚 Build Search Index
        run: node indexer.js

      - name: 💾 Commit Updated Database
        run: |
          git config --global user.name "AjadeshBot"
          git config --global user.email "ajadeshbot@users.noreply.github.com"

          git add raw-data.json
          git add index.json
          git add knowledge.json

          git commit -m "🤖 Mastermind X Bot updated search database" || echo "No changes to commit"

          git push
