name: Ajadesh Crawler

on:
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Ajadesh Crawler
        run: node crawler.js
